# Uncomment the next line to define a global platform for your project
platform :osx, '11.0'
install! "cocoapods", :preserve_pod_file_structure => true

target 'Example-CLT' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'ShibaInu', :path => '../'

end
